services:
  - type: web
    name: risk-assessment-app
    env: python
    repo: https://github.com/sharathchandra-9/Risk-Assessment-for-New-Policy-Applications
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
